Задание 6: Реализация кастомного связного списка
Ivan-Vorobev/java-kanban pull request #1
Opened 2024-05-23 00:24 UTC by Ivan-Vorobev

2024-05-23 09:25 UTC, TomattmanYandex requested changes
Привет, отлично, стоит еще добавить тесты таск менеджера, что если мы удаляем таск, то он также удаляется и из менеджера истории

2024-05-23 09:25 UTC, TomattmanYandex commented on src/services/history/memory/InMemoryHistoryManager.java
> +    private int nodeCnt = 0;
а зачем уже нужно количество?
можно узнать количество ключей в мапе, и будет тебе количество

2024-05-23 23:51 UTC, Ivan-Vorobev commented on src/services/history/memory/InMemoryHistoryManager.java
> +    private int nodeCnt = 0;
Начал с реализации двусвязного списка и потом не обратил внимание. FIXed

2024-05-24 07:22 UTC, TomattmanYandex approved these changes
Принято

2024-06-05 04:55 UTC, merged