Задание 8: Итоговое задание
Ivan-Vorobev/java-kanban pull request #3
Opened 2024-06-20 07:14 UTC by Ivan-Vorobev

2024-06-20 14:00 UTC, TomattmanYandex requested changes
Привет, хорошая работа, есть моменты на улучшение

2024-06-20 14:00 UTC, TomattmanYandex commented on src/services/repository/file/TaskRepository.java
> +        if (task.getStartTime() == null) {
есть короткая форма записи id прекрасно подходящая к таким случаям
условие ? что вернуть если true : что венуть если false
return task.getStartTime() == null ? "" : task.getStartTime().toString();

2024-06-20 14:00 UTC, TomattmanYandex commented on src/models/Task.java
> +    private Instant startTime;
зачем использовать instant когда есть localDateTime?

2024-06-20 14:00 UTC, TomattmanYandex commented on src/models/Task.java
> +    private Instant startTime;
Просто вопрос

2024-06-20 14:00 UTC, TomattmanYandex commented on src/services/task/memory/InMemoryTaskManager.java
> +        epic.setStatus(calculateEpicStatus(epic));
я бы порекомендовал вынести обновление статуса эпика и времени в отдельный метод, где убдут выполняться сразу оба действия

2024-06-20 14:00 UTC, TomattmanYandex commented on src/services/task/memory/InMemoryTaskManager.java
> +        epic.setStatus(calculateEpicStatus(epic));
точнее вызываться эти две команды

ведь они всегда будут идти парой

2024-06-20 14:00 UTC, TomattmanYandex commented on src/services/task/memory/InMemoryTaskManager.java
> +        if (task.getStartTime() != null) {
считается что чем меньше вложенность блоков кода, тем лучше для читаемости
можно в начале проверить не верные значения, и сразу выйти из метода, если с ними что то не так
if(task.getStartTime() == null) {
  return;
}
//обработка когда не null

2024-06-20 14:00 UTC, TomattmanYandex commented on src/services/task/memory/InMemoryTaskManager.java
> +                if (task.getEndTime().isBefore(prioritizedTask.getStartTime())) {
Вот тут выглядит немного странно, три условия того что таски не пересечены, обработаны по разному
почему бы все три условия не вынести в метод 
hasIntersection(Task task1, Task task2)
а уже в нем проверить
сначала что идентификаторы не равны
потом проверку из это строчки, 
а потом проверку из метода isIntersectStartTime

2024-06-20 14:00 UTC, TomattmanYandex commented on src/services/task/memory/InMemoryTaskManager.java
> +        if (!task1.getStartTime().isAfter(task2.getStartTime())) {
выглядит не очень логично, то что связанные условия разделены по разным методам
лучше сразу тут проверить сразу и время кончания и время старта
task1.getStarTime().isAfter(task2.getEndTime()) && task1.getEndTime().isBefore(task2.getStartTime()) будет значить что пересечений нету

2024-06-20 14:00 UTC, TomattmanYandex commented on src/services/task/memory/InMemoryTaskManager.java
> +        if (!subtasks.isEmpty()) {
тоже слегка тяжеловато для понимания

вариант как проще - сделать три метода которые очень похожи друг на друга

return subtasks.stream()
.map(Subtask::getStratTime)// или getDuration или getEndTime
.filter(Objects::notNull) //чтобы игнорить пустые значения
.sorted(/по возрастанию/)//для продолжительности не надо
.findFirst()//для времени окончания findLast для продолжительности - просуммировать

а тут 
List<Subtask> subtask = getEpicSubtasks(epic.getId());
epic.setStartTime(getEpicStartTIme(subtasks));
epic.setEndTime(getEpicEndTIme(subtasks));
epic.setDurationTime(getEpicDuration(subtasks));

2024-06-20 14:28 UTC, Ivan-Vorobev commented on src/models/Task.java
> +    private Instant startTime;
Так было в рекомендациях на QA наставника по разбору ТЗ

2024-06-20 14:59 UTC, Ivan-Vorobev commented on src/services/task/memory/InMemoryTaskManager.java
> +                if (task.getEndTime().isBefore(prioritizedTask.getStartTime())) {
здесь микро оптимизация на проверку для того чтобы не обходить весь список, так как он упорядочен по дате начала, поэтому это не пернести уже в метод  hasIntersection
```
if (task.getEndTime().isBefore(prioritizedTask.getStartTime())) {
                break;
            }
```

2024-06-21 11:45 UTC, TomattmanYandex approved these changes
Принято

2024-06-21 21:57 UTC, merged